#!/usr/bin/perl

use strict;
use warnings;

my $cp = shift @ARGV;
my $test = shift @ARGV;

my $res = qx/java -cp $cp:$cp\/antlr-4.5.1-complete.jar:$cp\/guava-18.0.jar tool.SRTool $test/;

print $res;
