#!/usr/bin/perl

use strict;
use warnings;

use Readonly;

Readonly my $TIMEOUT => 15;

my ($cp, $test) = @ARGV;

local $SIG{ALRM} = sub { die "UNKNOWN\n"; };

alarm($TIMEOUT);
my $res = qx/java -cp $cp:$cp\/antlr-4.5.1-complete.jar:$cp\/guava-18.0.jar tool.SRTool $test/;
alarm(0);

print $res;
exit 0;
